### ISSUE TITLE
Add persistent storage for SummonerService 

### ISSUE THREAD

**Issue by danielbedo** [danielbedo/riot4s#3]
Add something like SummonerServiceStoreComponent (ElasticSearch?). 
Not sure how we should handle the case if someone doesn't need it. 
As it is now: If the url is in the cache, the JSON response comes from the cache and the summonerService isn't even called. If it's not in the cache then the summonerService gets the response from the API.
After this ticket is finished:
If it's in the cache, same as before, summonerService not called.
If it's not in the cache then now we would need to first hit the persistent store for the summonerService and look for the entity in question. If found just return it, otherwise hit up the API and store the response in the store.
Not sure how to handle the case if someone doesn't need a persistent store for a given endpoint. Maybe have a NoopPersistentStorage that doesn't return anything?

**Comment by mstockerl** [comment]
This shouldn't be part of the API
